.\" Manpage for wingufile-client
.\" Contact info@clouidio.com to correct errors or typos.
.TH wingufile 1 "31 Jan 2013" "Linux" "wingufile-client man page"
.SH NAME
wingufile-applet \- start the wingufile client
.SH SYNOPSIS
wingufile-applet [OPTIONS]
.SH DESCRIPTION
.BR wingufile-applet
is the client program of wingufile. It will start
.BR ccnet(1)
, 
.BR seaf-daemon(1)
, 
.BR wingufile-web(1)
for you
.SH SEE ALSO
ccnet(1), seaf-daemon(1), wingufile-web(1), seaf-cli(1)
.SH AUTHOR
ClouidIO (info@clouidio.com)
.SH WEBSTIE
http://www.wingufile.com
.LP
https://github.com/haiwen/wingufile/
