.\" Manpage for wingufile-client
.\" Contact info@clouidio.com to correct errors or typos.
.TH wingufile 1 "31 Jan 2013" "Linux" "wingufile client man page"
.SH NAME
wingufile-web \- the local web interface for wingufile client
.SH SYNOPSIS
wingufile-web [OPTIONS]
.SH DESCRIPTION
.BR wingufile-web
starts the local web interface of the wingufile client.
It's started by wingufile-applet(1).
.SH SEE ALSO
ccnet(1), wingufile-applet(1), winguf-daemon(1), winguf-cli(1)
.SH AUTHOR
ClouidIO (info@clouidio.com)
.SH WEBSTIE
http://www.wingufile.com
.LP
https://github.com/haiwen/wingufile/
