.\" Manpage for wingufile-client
.\" Contact info@clouidio.com to correct errors or typos.
.TH wingufile 1 "31 Jan 2013" "Linux" "wingufile client man page"
.SH NAME
winguf-daemon \- the daemon of wingufile client
.SH SYNOPSIS
winguf-daemon [OPTIONS]
.SH DESCRIPTION
.BR wingufile-daemon
is the daemon of wingufile client.
It's started by wingufile-applet(1).
.SH SEE ALSO
ccnet(1), winguf-web(1), wingufile-applet(1), winguf-cli(1)
.SH AUTHOR
ClouidIO (info@clouidio.com)
.SH WEBSTIE
http://www.wingufile.com
.LP
https://github.com/haiwen/wingufile/
